bearer_token = "GET_KEY_FROM_developer.twitter.com/apps"
api_key = "GET_KEY_FROM_developer.twitter.com/apps"
api_secret = "GET_KEY_FROM_developer.twitter.com/apps"
access_token = "GET_KEY_FROM_developer.twitter.com/apps"
access_token_secret = "GET_KEY_FROM_developer.twitter.com/apps"
openai_key = "GET_YOUR_OPENAI_API_KEY_FROM_https://platform.openai.com/api-keys"
